export 'login_page.dart';
export 'splash_page.dart';
export 'shopping_page.dart';
export 'product_detail.dart';
export 'signup_page.dart';
export 'cart_page.dart';
export 'user_type_page.dart';
export 'dashboard_page.dart';
export 'package:mobile_ecommerce/pages/widgets//colors.dart';
